version: '3.8'
services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=boies2608
      - DOCKER_INFLUXDB_INIT_PASSWORD=26o82oo5
      - DOCKER_INFLUXDB_INIT_ORG=nhom_12
      - DOCKER_INFLUXDB_INIT_BUCKET=wed-game
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=zIGlnIr44LpdJnobJ68V8AHdzsWfaIShovlLY9m5ZDX3j_8SisNNq7BF-btVVgFuHMtlXEkswG0xoO0UoXcw4w==
    volumes:
      - ./db/influxdb-1/data:/var/lib/influxdb2
      - ./db/influxdb-1/config:/etc/influxdb2
  app1:
    build: .
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - INSTANCE_ID=app1
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_TOKEN=zIGlnIr44LpdJnobJ68V8AHdzsWfaIShovlLY9m5ZDX3j_8SisNNq7BF-btVVgFuHMtlXEkswG0xoO0UoXcw4w==
    depends_on:
      - influxdb

  app2:
    build: .
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
      - INSTANCE_ID=app2
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_TOKEN=zIGlnIr44LpdJnobJ68V8AHdzsWfaIShovlLY9m5ZDX3j_8SisNNq7BF-btVVgFuHMtlXEkswG0xoO0UoXcw4w==
    depends_on:
      - influxdb

  app3:
    build: .
    ports:
      - "3003:3000"
    environment:
      - PORT=3000
      - INSTANCE_ID=app3
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_TOKEN=zIGlnIr44LpdJnobJ68V8AHdzsWfaIShovlLY9m5ZDX3j_8SisNNq7BF-btVVgFuHMtlXEkswG0xoO0UoXcw4w==
    depends_on:
      - influxdb

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3

volumes:
  influxdb-data:
